version: "3.0"

services:
    h0h0h0:
        build: .
        environment:
            - FTP_PORT=5001
            - HTTP_PORT=5000
        ports:
            - "5000-5020:5000-5020"
        restart: on-failure
